### ISSUE TITLE
main_coop_vae.py文件运行异常/main_ Coop_ Vae.py file runs abnormally

### ISSUE THREAD

**Issue by CaiKaifen** [mrflogs/SHIP#1]
你好，在我运行main_coop_vae.py的时候，“import clip”和“from clip.simple_tokenizer import SimpleTokenizer as _Tokenizer”两行语句会报错，控制台显示“No module named 'clip'”和“No module named 'clip.simple_tokenizer'”。我尝试使用“pip install XXX”或者“conda install XXX”，都不能解决以上问题。请问您有什么方法解决这个问题吗？
Hello, when I run main_ Coop_ When using vae. py, the statements "import clip" and "from clip. simple_tokenizer import SimpleTokenizer as _Tokenizer" will generate an error, and the console will display "No module named 'clip'" and "No module named 'clip. simple_tokenizer'". I tried using 'pip install XXX' or 'conda install XXX', but none of them could solve the above problem. May I ask if you have any methods to solve this problem?

**Comment by Neko9810** [comment]
We have update clip folder. Please test to see if this work？

**Comment by mrflogs** [comment]
We have uploaded the clip folder. Please test to see if it works.

**Comment by CaiKaifen** [comment]
OK,thank you.
&nbsp;


机智如我
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月24日(星期一) 上午10:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mrflogs/SHIP] main_coop_vae.py文件运行异常/main_ Coop_ Vae.py file runs abnormally (Issue #1)





 
We have update clip folder. Please test to see if this work？

**Comment by CaiKaifen** [comment]
It works.Thank you.
&nbsp;


机智如我
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月24日(星期一) 上午10:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mrflogs/SHIP] main_coop_vae.py文件运行异常/main_ Coop_ Vae.py file runs abnormally (Issue #1)





 
We have uploaded the clip folder. Please test to see if it works.
