### ISSUE TITLE
About Tip-Adapter + SHIP

### ISSUE THREAD

**Issue by Nevaeh7** [mrflogs/SHIP#2]
This is an excellent and interesting work, in Base-to-new generalization Tip-Adapter+SHIP achieves excellent performance, could you please release the code for Tip-Adapter+SHIP, thanks!

**Comment by mrflogs** [comment]
Thank you for your interest. We may consider providing the code in the future. In the meantime, we encourage you to refer to the implementation of [Tip-Adapter](https://github.com/gaopengcuhk/Tip-Adapter) to develop the program.

**Comment by Nevaeh7** [comment]
> Thank you for your interest. We may consider providing the code in the future. In the meantime, we encourage you to refer to the implementation of [Tip-Adapter](https://github.com/gaopengcuhk/Tip-Adapter) to develop the program.

Thank you for your helpful answer
